import Head from 'next/head'
import Navbar from '@/components/Navbar'
import { HomePage } from './Home'
import "../styles/global.module.css"
import { ChakraProvider } from '@chakra-ui/react'
import theme from '@/theme/theme.js'
export default function Home() {
  return (
    <div className='body'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ChakraProvider theme={theme}>
      <Navbar/>
      <HomePage/>
      </ChakraProvider>
    </div>
  )
}
